version: '3.8'
services:
  oracle:
    image: gvenzl/oracle-xe:23-slim
    environment:
      - ORACLE_PASSWORD=changeit
      - ORACLE_DATABASE=XE
    ports:
      - 1521:1521
    healthcheck:
      test: ["CMD-SHELL","echo 'SELECT 1 FROM DUAL' | sqlplus sys/changeit@//localhost:1521/XE as sysdba"]
      interval: 30s
      retries: 10


  app:
    build: .
    depends_on:
      - oracle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521/XE
      - SPRING_DATASOURCE_USERNAME=APP_USER
      - SPRING_DATASOURCE_PASSWORD=changeit
      - JWT_SECRET=change-this-secret-in-dev
  ports:
    - 8080:8080