spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:APP_USER}
    password: ${SPRING_DATASOURCE_PASSWORD:changeit}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  server:
    port: 8080


  jwt:
    secret: ${JWT_SECRET:change-this-secret-in-dev}
    expiration-ms: 3600000


  flyway:
    enabled: true
    locations: classpath:db/migration


  logging:
    level:
      org.hibernate.SQL: DEBUG