CREATE TABLE ROLES (
                       ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       NAME VARCHAR2(50) UNIQUE NOT NULL
);


CREATE TABLE USERS (
                       ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       USERNAME VARCHAR2(100) UNIQUE NOT NULL,
                       PASSWORD VARCHAR2(255) NOT NULL,
                       FULL_NAME VARCHAR2(200),
                       ENABLED NUMBER(1) DEFAULT 1
);


CREATE TABLE USER_ROLES (
                            USER_ID NUMBER NOT NULL,
                            ROLE_ID NUMBER NOT NULL,
                            CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
                            CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);


CREATE TABLE ITEMS (
                       ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       NAME VARCHAR2(200) NOT NULL,
                       DESCRIPTION VARCHAR2(2000),
                       QUANTITY NUMBER DEFAULT 0,
                       CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);


INSERT INTO ROLES (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (NAME) VALUES ('ROLE_USER');


-- Insira um usuário admin com senha BCRYPT (ex.: senha 'admin'). Substitua o hash antes de uso.
INSERT INTO USERS (USERNAME, PASSWORD, FULL_NAME, ENABLED) VALUES ('admin', '$2a$10$u1GfZQbF7f9uYwqj1aKQNe0zY5q9Pz1E2sHcKxq3Yd7mNf1p0X0yK', 'Administrador', 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);